stages:          
  - build
  - test
  - deploy

build-job:       
  stage: build
  script:
    - echo "Build stage is running successfully."
  
test-job:  
  stage: test    
  script:
    - echo "Test stage is running successfully."


deploy-job:      
  stage: deploy  
  environment: test
  script:
    - echo "Deploying application is running sucessfully."
