services:
  usage:
    build:
      context: ./sensors/usage
    networks:
      - fc_network
    environment:
      - PORT=5555
  temperature:
    build:
      context: ./sensors/temperature
    networks:
      - fc_network
    environment:
      - PORT=5556
  edge:
    build:
      context: .
      dockerfile: edge.Dockerfile
    command: 'cloud:8080 temperature:5556 usage:5555'
    networks:
      - fc_network
  cloud:
    build:
      context: .
      dockerfile: cloud.Dockerfile
    ports:
      - 8080:8080
    networks:
      - fc_network
    command: '-p=8080'
    
networks:
  fc_network:
    driver: bridge
